# Generated by Django 3.0.4 on 2020-03-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='costomer_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rooms_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('time_in', models.CharField(max_length=100)),
                ('time_out', models.CharField(max_length=100)),
                ('date_opted', models.CharField(max_length=100)),
                ('is_booked', models.BooleanField()),
                ('user_booked', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
