# Generated by Django 3.2.16 on 2023-04-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms_added',
            old_name='end_room',
            new_name='is_booked',
        ),
        migrations.RenameField(
            model_name='rooms_added',
            old_name='start_room',
            new_name='room_number',
        ),
    ]
