# Generated by Django 3.2.16 on 2023-04-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20230427_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='picture_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='picture',
            field=models.FileField(upload_to='static/images/'),
        ),
    ]
