# Generated by Django 3.0.4 on 2020-03-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_manager_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='added_rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_room', models.IntegerField()),
                ('end_room', models.IntegerField()),
                ('in_time', models.CharField(max_length=100)),
                ('out_time', models.CharField(max_length=100)),
                ('buffer_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rooms_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('room_id', models.IntegerField()),
                ('date_booking', models.DateField()),
                ('date_opted', models.CharField(max_length=100)),
                ('time_booking', models.TimeField()),
                ('time_opted', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
