# Generated by Django 3.2.16 on 2023-04-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20230428_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='picture_name',
            field=models.FileField(upload_to=''),
        ),
    ]
