# Generated by Django 3.2.16 on 2023-04-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20230428_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms_added',
            name='room_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rooms_added',
            name='room_picture',
            field=models.FileField(default='static/images/room.png', upload_to='static/images/'),
        ),
    ]
