# Generated by Django 3.2.16 on 2023-04-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_alter_rooms_added_room_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms_added',
            name='default_path',
            field=models.FileField(default='static/images/rooms/default_room.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='rooms_added',
            name='room_picture',
            field=models.FileField(default=0, upload_to='static/images/rooms/'),
        ),
    ]
