# Generated by Django 3.2.16 on 2023-05-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0012_remove_rooms_booked_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms_booked',
            name='end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='rooms_booked',
            name='hotel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rooms_booked',
            name='owner',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rooms_booked',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rooms_booked',
            name='room_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rooms_booked',
            name='start',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='rooms_booked',
            name='user_booked',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
