# Generated by Django 3.2.16 on 2023-05-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_auto_20230504_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms_booked',
            name='end',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='rooms_booked',
            name='hotel',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='rooms_booked',
            name='owner',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='rooms_booked',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='rooms_booked',
            name='room_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='rooms_booked',
            name='start',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='rooms_booked',
            name='user_booked',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
