# Generated by Django 3.2.16 on 2023-05-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0016_alter_rooms_booked_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms_booked',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
